### ISSUE TITLE
stack trace running on kube

### ISSUE THREAD

**Issue by gamykla** [jelis/security-cam#1]
2016-10-01 21:11:38,970 - werkzeug - INFO - 10.2.16.0 - - [01/Oct/2016 21:11:38] "POST /captures/ HTTP/1.1" 401 -
Traceback (most recent call last):
  File "/security_cam/cam_server.py", line 60, in <module>
    app.run(host="0.0.0.0", port=8080, debug=False)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

**Comment by gamykla** [comment]
what the fuck

NAME                                    READY     STATUS             RESTARTS   AGE
camserver-deployment-3185789073-5uu4l   1/1       Running            13         1d
camserver-deployment-3185789073-hlt91   0/1       CrashLoopBackOff   12         1d
camserver-deployment-3185789073-vb16n   0/1       CrashLoopBackOff   13         1d
camserver-deployment-3185789073-x4jm0   0/1       CrashLoopBackOff   13         1d
